version: '3.7'

services:
  test-jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: test-jenkins
    image: dedisalam/test-jenkins
    ports:
      - '10000:80'
    restart: 'unless-stopped'
    networks:
      - test-jenkins

networks:
  test-jenkins:
    name: test-jenkins
