version: '3.7'

services:
  test-jenkins:
    container_name: test-jenkins
    image: dedisalam/jenkins
    ports:
      - '10000:80'
    restart: 'unless-stopped'
    networks:
      - test-jenkins

networks:
  test-jenkins:
    name: test-jenkins
